use Univer;

--1
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
	   FROM PULPIT, FACULTY 
       WHERE PULPIT.FACULTY = FACULTY.FACULTY
       AND 
	   FACULTY.FACULTY IN
       (
			SELECT DISTINCT PROFESSION.FACULTY 
	        FROM PROFESSION
	        WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологи%' )
       )

--2
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
	   FROM PULPIT INNER JOIN FACULTY 
	   ON PULPIT.FACULTY = FACULTY.FACULTY
			WHERE FACULTY.FACULTY IN
			(
				 SELECT DISTINCT PROFESSION.FACULTY 
				 FROM PROFESSION
				 WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологи%')
			)

--3
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
	   FROM PULPIT INNER JOIN FACULTY 
	   ON PULPIT.FACULTY = FACULTY.FACULTY
			INNER JOIN PROFESSION
			ON FACULTY.FACULTY = PROFESSION.FACULTY
			WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологи%')

--4 список аудиторий самых больших вместимостей
SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
	   FROM AUDITORIUM t1
		    WHERE t1.AUDITORIUM_NAME = 
			(
				  SELECT TOP(1) AUDITORIUM_NAME 
						 FROM AUDITORIUM t2
						 WHERE t2.AUDITORIUM_TYPE = t1.AUDITORIUM_TYPE
							   ORDER BY AUDITORIUM_CAPACITY desc
			)

--5 список наименований факультетов, на котором нет ни одной кафедры
SELECT FACULTY.FACULTY FROM FACULTY
	   WHERE not exists
	   (
			SELECT * FROM PULPIT 
				   WHERE FACULTY.FACULTY = PULPIT.FACULTY
	   )

--6
SELECT top 1
	   (SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			  WHERE PROGRESS.SUBJECT LIKE 'ОАиП') [ОАиП],
	   (SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			  WHERE PROGRESS.SUBJECT LIKE 'БД') [БД],
	   (SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			  WHERE PROGRESS.SUBJECT LIKE 'СУБД') [СУБД]
FROM PROGRESS

--7опр тип аудиторий, вместимость которых больше чем аудитоиии, в навании типa которых есть ЛБ
SELECT AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY 
       FROM AUDITORIUM 
	   WHERE AUDITORIUM.AUDITORIUM_CAPACITY >= ALL (
			 SELECT AUDITORIUM_CAPACITY  FROM AUDITORIUM
					WHERE AUDITORIUM_TYPE LIKE 'ЛБ%')

--8
SELECT AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY 
       FROM AUDITORIUM 
	   WHERE AUDITORIUM.AUDITORIUM_CAPACITY > ANY (
			 SELECT AUDITORIUM_CAPACITY  FROM AUDITORIUM
					WHERE AUDITORIUM_TYPE LIKE 'ЛБ%')